-- From old ass database to level 0
-- schema generated by sqlalchemy
CREATE TABLE user (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        username VARCHAR NOT NULL,
        admin BOOLEAN NOT NULL,
        password_hash VARCHAR,
        oauth_info VARCHAR,
        UNIQUE (id),
        UNIQUE (username),
        CHECK (admin IN (0, 1))
);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE request (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        status VARCHAR(8) NOT NULL,
        type VARCHAR(6) NOT NULL,
        name VARCHAR NOT NULL,
        description VARCHAR,
        requester_id INTEGER NOT NULL,
        packager_id INTEGER,
        pub_date DATE NOT NULL,
        note VARCHAR,
        UNIQUE (id),
        CONSTRAINT requeststatus CHECK (status IN ('OPEN', 'DONE', 'REJECTED')),
        CONSTRAINT requesttype CHECK (type IN ('PAKREQ', 'UPDREQ', 'OPTREQ')),
        FOREIGN KEY(requester_id) REFERENCES user (id),
        FOREIGN KEY(packager_id) REFERENCES user (id)
);
