.print 'Creating new tables...'
-- oauth table generated by sqlalchemy
CREATE TABLE oauth (
        uid INTEGER NOT NULL,
        type VARCHAR(8) NOT NULL,
        oid VARCHAR,
        token VARCHAR,
        PRIMARY KEY (uid, type),
        FOREIGN KEY(uid) REFERENCES user (id),
        CONSTRAINT oauthtype CHECK (type IN ('Telegram', 'GitHub', 'AOSC'))
);

-- user table generated by sqlalchemy
CREATE TABLE user_x (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        username VARCHAR NOT NULL,
        admin BOOLEAN NOT NULL,
        password_hash VARCHAR,
        UNIQUE (id),
        UNIQUE (username),
        CHECK (admin IN (0, 1))
);

.print 'Copying data from old tables to new tables...'
.print '    -- OAuth data...'
INSERT INTO oauth SELECT id, 'Telegram', json_extract(oauth_info, '$.telegram_id'), NULL FROM user;
INSERT INTO oauth SELECT id, 'GitHub', json_extract(oauth_info, '$.github_id'), NULL FROM user;
INSERT INTO oauth SELECT id, 'AOSC', json_extract(oauth_info, '$.aosc_id'), NULL FROM user;

.print '    -- User profiles...'
INSERT INTO user_x SELECT id, username, admin, password_hash FROM user;

.print 'Rotating tables...'
DROP TABLE user;
ALTER TABLE user_x RENAME TO user;

.print 'Migration finished!'
