db:
  host: "localhost"
  username: "app"
  password: "password"
  database: "pakreq"

telegram:
  token: ""

host: 127.0.0.1
port: 8080
base_url: "http://localhost:8080"
ldap_url: "ldaps://localhost/"
